"use client";
import {useState} from "react";
const phases=[['01','Descubrimiento','Monitoriza y selecciona','12 fuentes'],['02','Evidencia','Ingiere, transcribe y verifica','67%'],['03','Investigación','Cruza, deduplica y redacta','Pendiente'],['04','Producción','Voz, visuales y montaje','Pendiente'],['05','Publicación','QA, SEO y exportación','Pendiente']];
const evidence=[['NASA Spaceflight','Prueba estática del vehículo','96','VERIFICADO'],['FAA / NOTAM','Ventana operativa publicada','100','VERIFICADO'],['Marcus House','Fecha tentativa de lanzamiento','71','PROBABLE'],['X · fuente sin atribuir','Cambio interno de motores','28','NO DEMOSTRADO']];
export default function Home(){const[tab,setTab]=useState('Pipeline');const[open,setOpen]=useState(false);const[area,setArea]=useState('Ingeniería aeroespacial');const[msg,setMsg]=useState('');const flash=(x:string)=>{setMsg(x);setTimeout(()=>setMsg(''),2200)};return <div className="shell">
<aside><div className="brand"><strong>N<span>R</span></strong><b>Research Studio<small>by norug.es</small></b></div><nav>{['⌂  Centro de mando','◇  Investigaciones  · 4','⌁  Fuentes','▱  Biblioteca','—  PRODUCCIÓN','◎  Guiones','▷  Media Studio','↗  Publicaciones','—  SISTEMA','⬡  Proveedores IA','⚙  Configuración'].map((x,i)=><button className={i===0?'active':''} key={x}>{x}</button>)}</nav><div className="plan"><em>PLAN PRO</em><b>18.420 / 50k créditos</b><i/><small>Se renueva en 12 días</small></div><div className="user"><i>MR</i><b>Moisés Ramos<small>Workspace NoRug</small></b></div></aside>
<main><header><span>Investigaciones　/　Briefing semanal aeroespacial</span><div>⌕　♢　 <b>● Sistema operativo</b></div></header>
<section className="hero"><div><em>EN EJECUCIÓN　· EPISODIO 024</em><h1>Briefing semanal aeroespacial</h1><p>Investigación multi-fuente · {area} · ES</p></div><div><button onClick={()=>flash('Ejecución pausada de forma segura')}>Ⅱ Pausar</button><button className="primary" onClick={()=>setOpen(true)}>＋ Nueva investigación</button></div></section>
<section className="metrics"><article><small>PROGRESO GLOBAL</small><b>38% <em>+12% hoy</em></b><i><u style={{width:'38%'}}/></i></article><article><small>FUENTES PROCESADAS</small><b>8 <span>/ 12</span></b><p>6 vídeo · 2 documentos</p></article><article><small>EVIDENCIAS VERIFICADAS</small><b>2 <span>/ 4</span> <em>87% confianza</em></b><p>1 afirmación requiere revisión</p></article><article><small>TIEMPO HUMANO AHORRADO</small><b>14h 32m <em>↑ 73%</em></b><p>Estimado frente a flujo manual</p></article></section>
<div className="tabs">{['Pipeline','Evidencias','Fuentes','Actividad'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}{t==='Evidencias'&&'　24'}</button>)}</div>
{tab==='Pipeline'&&<section className="grid"><div className="panel"><div className="title"><div><h2>Pipeline de investigación</h2><p>17 pasos auditables · 3 puntos de control humano</p></div><button>Ver dependencias ↗</button></div><div className="phases">{phases.map((p,i)=><article className={i===0?'done':i===1?'run':''} key={p[0]}><i>{i===0?'✓':p[0]}</i><div><small>FASE {p[0]}</small><h3>{p[1]}</h3><p>{p[2]}</p></div><u><b/></u><div><b>{p[3]}</b><small>{i===0?'Completada':i===1?'Procesando transcripciones':'En cola'}</small></div>{i===1&&<button onClick={()=>setTab('Evidencias')}>Revisar evidencia</button>}</article>)}</div></div><div className="side"><div className="panel live"><div className="title"><div><h2>Ahora mismo</h2><p>● Actividad en vivo</p></div></div><div className="job"><i>◌</i><div><small>TRANSCRIPCIÓN · PASO 05</small><b>Starbase Weekly Update.mp4</b><u><em/></u><p>67% · 08:42 restante</p></div></div><div className="queue">EN COLA <b>2</b><p>FAA briefing.pdf · @SpaceX stream</p></div></div><div className="panel quality"><h2>Controles de calidad</h2><p>Fuentes primarias <b>78%</b></p><i><u style={{width:'78%'}}/></i><p>Cobertura de citas <b>92%</b></p><i><u style={{width:'92%'}}/></i><p>Riesgo de redundancia <b>Bajo</b></p><button onClick={()=>setTab('Evidencias')}>Abrir centro de evidencias</button></div></div></section>}
{tab==='Evidencias'&&<section className="panel evidence"><div className="title"><div><h2>Centro de evidencias</h2><p>Fuente, captura, hash SHA-256, custodia y confianza por afirmación.</p></div><button onClick={()=>flash('Manifiesto de evidencias generado')}>Exportar manifiesto</button></div><div className="table"><div className="tr head"><span>Fuente</span><span>Afirmación</span><span>Confianza</span><span>Clasificación</span></div>{evidence.map(e=><div className="tr" key={e[0]}><b>{e[0]}<small>Artefacto capturado</small></b><span>{e[1]}</span><b>{e[2]}%</b><em className={+e[2]<50?'bad':+e[2]<90?'prob':''}>{e[3]}</em></div>)}</div></section>}
{(tab==='Fuentes'||tab==='Actividad')&&<section className="panel empty"><strong>⌁</strong><h2>{tab}</h2><p>{tab==='Fuentes'?'Conectores para YouTube, Twitch, RSS, web, documentos y APIs personalizadas.':'Auditoría de decisiones, ejecuciones, aprobaciones y costes.'}</p><button className="primary" onClick={()=>flash('Acción guardada')}>{tab==='Fuentes'?'＋ Añadir fuente':'Exportar actividad'}</button></section>}
</main>{open&&<div className="back" onMouseDown={()=>setOpen(false)}><form onMouseDown={e=>e.stopPropagation()} onSubmit={e=>{e.preventDefault();setOpen(false);flash('Investigación creada como borrador')}}><button type="button" className="close" onClick={()=>setOpen(false)}>×</button><em>NUEVA INVESTIGACIÓN</em><h2>Define el campo, no el proveedor</h2><p>El pipeline adapta fuentes, criterios y salida al área elegida.</p><label>Nombre del proyecto<input defaultValue="Radar semanal" required/></label><label>Área de investigación<input value={area} onChange={e=>setArea(e.target.value)} required/></label><div><label>Idioma<select><option>Español</option><option>English</option></select></label><label>Salida<select><option>Vídeo documental</option><option>Informe técnico</option><option>Podcast</option></select></label></div><label className="check"><input type="checkbox" defaultChecked/> Exigir aprobación humana antes de publicar</label><button className="primary submit">Crear investigación</button></form></div>}{msg&&<div className="toast">✓ {msg}</div>}</div>}
